### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by mvmcjr** [EdonGashi/Material.Application#1]
Hey, this library is pretty cool! It would be awesome if it had its own NuGet package!

**Comment by edongashi** [comment]
Attempting now. I'm terrible at publishing so it will likely break at first.

**Comment by edongashi** [comment]
Noticed that you created a fork. If you like you can publish (and/or maintain) the project from your version, or I can grant you push permissions here.

**Comment by mvmcjr** [comment]
Yeah, I've played a bit with the appveyor stuff, I'll post the build yaml at my lunchtime!

**Comment by mvmcjr** [comment]
@EdonGashi Hey [I've added the package](https://www.nuget.org/packages/Material.Application/)! But I don't have permission to set up hooks so for now, the build has to be manually triggered on vsts.

**Comment by edongashi** [comment]
That's great, thank you! Feel free to push anything you think is necessary. What do we need to setup the webhooks? If there's any secret key or stuff you can email me at edongashi@hotmail.co.uk

**Comment by mvmcjr** [comment]
@EdonGashi Usually GitHub does this automatically, and although we use a token it would be best if you had a Microsoft account, cause then I can add you into the vsts project and you can then link your account to the build

**Comment by edongashi** [comment]
Registered using the above email. There won't be a lot of updates at the moment so it's okay either way.
